### ISSUE TITLE
Crystal Lens isn't increasing litherite and erodium drops

### ISSUE THREAD

**Issue by DerpityDoo** [DarkPacks/SevTech-Ages#1906]
After running two void ore miners, one with a crystal lens and one with a clear lens, for about 8 hours I received the same number of Environmental Tech crystals from both miners, ±2.

## Expected Behavior
I would expect almost 10x the amount of litherite from the miner with a crystal lens, according to JEI

## Steps to Reproduce (for bugs)
1. Set up 2 tier 1 miners, one with clear and one with crystal lens
2. Look at the Environmental Tech crystals (not) coming in

## Client Information
* Modpack Version: 3.0.6
* Java Version: jdk1.8.0_144
* Launcher Used: Twitch
* Memory Allocated: 12G (max in launcher setting)
* Optifine Installed?: yes

**Comment by futileohm** [comment]
I ran into the same thing, it appears all lenses are broken in the latest version of Environmental Tech. Reportedly fixed in the next version but no news on when that'll release.

https://github.com/ValkyrieofNight/EnvironmentalTech/issues/116

**Comment by artdude543** [comment]
Fixed in 3.0.7

**Comment by lbrandy** [comment]
I don't think this was fixed in 3.0.7. The changelog for envtech seems to indicate it was fixed in 2.0.10a (released today) and we are still on 2.0.9c. I double checked with a quick test and don't see much change in erodium rate for a t1 miner.

**Comment by artdude543** [comment]
We had downgraded doe to other issues. And did not update this issue. But yes it's not fixed as of yet.

**Comment by WibbersGIT** [comment]
@artdude543 You mentioned you had downgraded for other issues in 3.0.7. Do you recall what the issues were? I would like to update the mod in my pack manually to correct this issues as opposed to waiting for 3.0.8, just wondering if they were major issues.

**Comment by Kyra1509** [comment]
I'm still experiencing this issue, using 3.0.7. Though I've never used this mod before, just checking that I do place the crystal laser between the two laser cores, yes? I've never had a lower version than 3.0.7 so wouldn't have to a JSON reload.
