### ISSUE TITLE
Geolosys lag when mining ores

### ISSUE THREAD

**Issue by RadGH** [DarkPacks/SevTech-Ages#3933]
## Bug Report
It seems to be exactly the same issue as described by #1559 which was closed over a year ago. I don't see a solution for the current version. I've also checked reddit but I am not sure if this is a popular issue anymore.

We just reached the first age. Mining coal ore, after breaking the block the block reappears for a moment and then breaks a second time, yielding the ore. The server is not under a lot of stress and nothing else is lagging.

Just like the issue from last year, switching to another tool after breaking a block will prevent the block from breaking a second time. You can wait several seconds, then switch back to your pickaxe, and the block will then break.

## Expected Behaviour
The block shouldn't reappear and be so buggy

## Possible Solution
I don't know of any. Updating Geolosys and other mods seemed to be the solution last year but I am still experience the issue.

## Steps to Reproduce (for bugs)
1. Break coal ore.
2. It reappears.
3. Wait for it to really break.

## Logs
* Client/Server Log: latest.log file: https://pastebin.com/3Xmtka05

I have a debug log but it's 141mb. No crash log is relevant

## Client Information
* Modpack Version: 3.1.2 hotfix 1
* Java Version: 1.8.0_221
* Launcher Used: Twitch
* Memory Allocated: 8192mb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 I think
* Additional Content Installed: None

## Server Information
* Java Version: I don't know but the server instance was created 14 days ago so it's probably pretty recent.
* Operating System: Not sure
* Hoster/Hosting Solution: ServerMiner Gold
* Sponge (Non-Vanilla Forge) Server: Not sure

**Comment by coldino** [comment]
I had the same issue. Testing with FDP disabled/blacklisted sometimes fixed it temporarily, but didn't seem to be the root cause and I found it impossible to narrow down the exact circumstances that cause it.

It just went away as the pack progressed. Very annoying in the early stages though.

**Comment by tibbe78** [comment]
I fixed this problem by installing the mod randompatches, and only enabling the client server patches in the config. Here is my version, same config on client and server. 
https://pastebin.com/raw/sZNLZ2LB

**Comment by Sadumon** [comment]
Having similar issues.  Coal that "appeared" near my base after I hit age 1 had this issue initially.  It would take approximately one second after breaking the coal block for it to actually drop the coal (during which time the block would pop back). If I swapped out from my pickaxe during that delay, the block would stay unbroken until I swapped back to my pickaxe.

Restarting the server did seem to fix the issue with that particular coal vein, but when I went to a brand new area that had not been explored before and found one of the tin veins, I had the same issue.  I have not tried restarting the server again to see if that resolves the issue with that particular vein.

Unfortunately, installing an additional mod that requires both server and client as @tibbe78 suggests as a possible workaround is not a solution for me as getting all of the players on the server to do the install isn't practical.

**Comment by cproo12** [comment]
Anybody figure this out yet? Running into the same problem with latest version of sevtech. Going to try randompatches on server side only and see if that does the trick because not all of my players are going to want to have to install it.

**Comment by sam-kirby** [comment]
If you're really on the latest version, your players and server already have random patches.

**Comment by cproo12** [comment]
Huh yep just noticing this... Still having the problem though. Any ideas?

**Comment by RadGH** [comment]
@cproo12 It's been forever since I played but going to a new chunk and mining was the best fix for me. And that became necessary when looking for new ores anyway.

**Comment by cproo12** [comment]
@RadGH Okay, that's what I will do for now. I thought I lucked out by making my base in the middle of a bunch of ores, but not so much :)

Also, to the pack devs: Having a blast playing through this pack by the way, I played a year ago but burned out and didn't get out of Age 0, now absolutely loving it in age 2 with two of my friends. The best progression based pack I have ever played!

**Comment by RadGH** [comment]
Trying SevTech Ages of the Sky two years after I created this ticket and the problem is still exactly the same in this version of the modpack too.

Here's a video demonstrating it: https://radleysustaire.com/s3/82a78f/

**Comment by GamesGrandpa** [comment]
Currently on version 3.2.3. This issue persists through restarts of the client and server for me. Azurite Cassiterite Coal and Hematite were all fine for me, but gold has the block lag for me. My friend found a patch of coal that he was getting block lag on, but, again, mine was fine. They were both loaded before anyone reached Age 1 so I dont believe it to be an issue with ages. All ores that we have mined have been in chunks loaded prior to the age required for discovery. This bug also persists with ores placed down by the player. I placed gold that I spawned in and when I broke it it still had the issue. I also tried placing it in a different chunk. Still no dice. I also went to the beneath to see if it was a problem with the dimension, but, again, no change. I also tried to mine coal again and it now has block lag for me too. A very frustrating problem to have...

**Comment by Gerdathlete** [comment]
Still experiencing this issue. Version 3.2.3. I guess it will not get patched. Was not fixed with server restart.

**Comment by RadGH** [comment]
@Gerdathlete In case you missed [my comment above](https://github.com/DarkPacks/SevTech-Ages/issues/3933#issuecomment-708853823), if you go to a newly discovered chunk the issue might go away. I know it's not ideal, I just thought I should suggest it. Sorry though, shame this is still a problem.

**Comment by Tander** [comment]
+1 for this issue

**Comment by igorft3** [comment]
Try updating the Geolosys mod to the current one, I have set version 3.0. 12 and everything works, but I have not yet moved to another era and I need to check the generation of new ores.

**Comment by MalyasovDV** [comment]
For some reason the lag depends on the time it takes you to break the block, so if you are really annoyed by this you can just give yourself haste 50 effect
