### ISSUE TITLE
World Generation Causes crashes in The Twilight, Beneath and Betweenlands

### ISSUE THREAD

**Issue by Chronosmage** [DarkPacks/SevTech-Ages#4450]
## Bug Description

When a player enters any of the three dimesnions mentioned in the title, when generating new or existing chunks server TPS Takes a severe drop and eventually crashes the server (or our watchdog detects the hanging Ticks and will perceive the server as crashes, in most cases it does lock up)  

### Did this behavior use to work in the previous version?

Yes, this has been a problem in all versions 

## Steps to Reproduce (for bugs)

1. Have a player enter the Twilight, Betweenlands or Beneath
2.Walkarround and let the world load
3.Let the world load in
4. Server will take a tps drop
5. Finally the server will crash

If you need anymore info i can provide, We are in the process of pregenerating worlds in the hope that this will quell some issues So far nothing we have done has worked 

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/vCFZW2qv 
* https://pastebin.com/7PBJkRDc
* https://pastebin.com/m3BrtGF8
* https://pastebin.com/BWVrEG32
(had lots of crashes, the sever will crash at least 10 to 18 times per day, the majority of these crashes are down to world generation, topography etc, (in which case there's not a lot i can do) 

## Client Information
* Modpack Version:Beta 1
* Java Version:openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
* Launcher Used:Any
* Memory Allocated:8gb-10gbs (adapative) 
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:Beta 1 
* Additional Content Installed:No

## Server Information
* Java Version:openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
* Operating System:Ubuntu 18.04 LTS
* Hoster/Hosting Solution:Self-Managed Dedicated Server
* Sponge (Non-Vanilla Forge) Server:Yes

**Comment by TheFlash787** [comment]
Thanks Chronos for creating this. Just to add onto this, we have attempted adding more memory during these crashes - and this behaviour has also been experienced on a testing server where we attempted to pregenerated worlds on a separate server with at least 12GB+ to play with. Our machine is running the Intel i9 9900K so I feel that the issue is down to Topography’s unoptimised code (of which is no longer being developed) rather than the performance of the machine itself.

I hope that helps.
Thanks

**Comment by TheFlash787** [comment]
To add further information, this will also occur in the nether due to the IslandV2 generation. 

A very similar issue was reported back in October regarding Topography’s island v2 generation causing issues such as crashing and lag - however was reported as resolved in Alpha 4 - but the issue with Topography still exists. https://github.com/DarkPacks/SevTech-Ages/issues/4338

**Comment by Korenn** [comment]
We have experienced this crash many times as well on our server. Sometimes it can even randomly trigger when nobody is doing any exploring at all and is just standing around in our base.

We've reduced the occurance of the crashes by increasing the watchdog timeout to 2 minutes instead of 1. (this is a standard minecraft setting in server properties). But it still happens on occasion.

Unfortunately the crash reports give no clue as to what mod is causing the stall.
